# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mhaziza <mhaziza@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/11/17 10:27:35 by mhaziza           #+#    #+#              #
#    Updated: 2016/11/17 10:58:49 by mhaziza          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC      =   gcc
RM      =   rm -f
NAME	=	libft.a
SRCS    =   ./srcs/ft_putchar.c \
			./srcs/ft_putstr.c \
			./srcs/ft_strlen.c \
			./srcs/ft_strcmp.c \
			./srcs/ft_swap.c \

OBJS    =   ft_putchar.o \
			ft_putstr.o \
			ft_strlen.o \
			ft_strcmp.o \
			ft_swap.o \

all:	$(NAME)
$(NAME) :
	$(CC) -c $(SRCS) -I/includes
	ar rc $(NAME) $(OBJS)
	ranlib $(NAME)
clean:
	$(RM) $(OBJS)
fclean:	clean
	$(RM) $(NAME)
re:		fclean all

.PHONY:     all clean fclean re
